/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package music;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.io.File;
import java.io.FileInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.value.ChangeListener;
import javafx.beans.value.ObservableValue;
import javax.sound.sampled.FloatControl;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javazoom.jl.player.advanced.AdvancedPlayer;
import javax.sound.sampled.*;
import javax.swing.JSlider;
import javazoom.jl.player.*;
import bddMusic.conector;
import java.sql.SQLException;
import java.util.LinkedList;
import org.omg.PortableInterceptor.SYSTEM_EXCEPTION;
import Modelo.Reproduciendo;
import java.util.ArrayList;
import javazoom.jl.decoder.JavaLayerException;
import Modelo.Lista;
/**
 *
 * @author victorsalazar
 */
public class MusicGalery extends javax.swing.JFrame implements Runnable {

    Thread hilo1;
    Thread hilo2;
    Thread  hilo3= new Thread(this);
    Thread hilo4 = new Thread(this);
    conector cn;
    public Mixer mixer;
    FloatControl floco;
    int conta = 0;
    int columna = 0;
    AdvancedPlayer reproductor;
    DefaultTableModel modelo;
    String cortar;
    boolean activo= false,Pausec=false;
    ArrayList<Lista> marcador;
    /**
     * Creates new form MusicGalery
     */
    File archivo;

    public MusicGalery(conector Conector) {
        initComponents();
cn =Conector;
        setSize(790, 420);
        setLocationRelativeTo(this);
        setResizable(false);
marcador = new ArrayList<>();
        try {
            this.cn = new conector();
        } catch (Exception e) {
        }

     
        jPanel1.setVisible(false);
        modelo = (DefaultTableModel) jTable1.getModel();
        jSlider1.setValue(100);
        jSlider1.setForeground(Color.red);
        jSlider1.setInverted(false);
        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setPaintTicks(true);
        Vol.setText("Vol : " + jSlider1.getValue());
        jSlider1.setPaintLabels(true);

    
        
        opciones.setComponentOrientation(ComponentOrientation.RIGHT_TO_LEFT);
        img1.setVisible(true);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(false);
        img5.setVisible(false);
        img6.setVisible(false);
        hilo4.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        pause = new javax.swing.JButton();
        Marcadores = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        NombreMusic = new javax.swing.JLabel();
        verLista = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Vol = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        img1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        opciones = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel4.setText("X");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 0, 20, 20);

        jButton5.setText("Reguetton");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(0, 30, 90, 40);

        jButton6.setText("Salsa");
        jPanel1.add(jButton6);
        jButton6.setBounds(0, 60, 90, 40);

        jButton7.setText("Bachata");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(0, 90, 90, 40);

        jButton8.setText("Merenguez");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(0, 120, 90, 40);

        jButton9.setText("Lista");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(0, 160, 90, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(320, 40, 90, 200);

        jButton1.setText("<--");
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 280, 150, 23);

        pause.setText("|>");
        pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseActionPerformed(evt);
            }
        });
        getContentPane().add(pause);
        pause.setBounds(150, 280, 90, 23);

        Marcadores.setText("MARCADORES");
        Marcadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcadoresActionPerformed(evt);
            }
        });
        getContentPane().add(Marcadores);
        Marcadores.setBounds(280, 10, 120, 23);

        jButton3.setText("-->");
        getContentPane().add(jButton3);
        jButton3.setBounds(250, 280, 150, 23);

        NombreMusic.setForeground(new java.awt.Color(255, 255, 255));
        NombreMusic.setText("No audio");
        getContentPane().add(NombreMusic);
        NombreMusic.setBounds(10, 10, 343, 22);

        verLista.setText("LISTA");
        verLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verListaActionPerformed(evt);
            }
        });
        getContentPane().add(verLista);
        verLista.setBounds(0, 250, 400, 23);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 40);

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        getContentPane().add(jSlider1);
        jSlider1.setBounds(10, 310, 310, 60);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Lista De Reproduccion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setAutoscrolls(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(410, 10, 370, 360);

        Vol.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(Vol);
        Vol.setBounds(340, 310, 50, 40);

        img6.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\2img.jpg")); // NOI18N
        getContentPane().add(img6);
        img6.setBounds(0, 40, 410, 170);

        img5.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\4img.jpg")); // NOI18N
        getContentPane().add(img5);
        img5.setBounds(0, 40, 410, 170);

        img4.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\3img.jpg")); // NOI18N
        img4.setText("jLabel5");
        getContentPane().add(img4);
        img4.setBounds(0, 40, 410, 170);

        img3.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\5img.jpg")); // NOI18N
        img3.setText("jLabel5");
        getContentPane().add(img3);
        img3.setBounds(0, 40, 410, 170);

        img2.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\7img.png")); // NOI18N
        getContentPane().add(img2);
        img2.setBounds(0, 40, 410, 170);

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 40, 400, 200);

        img1.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\8img.jpg")); // NOI18N
        getContentPane().add(img1);
        img1.setBounds(0, 40, 410, 170);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\victorhugo\\Documents\\victor\\pc sony\\c\\documentos\\NetBeansProjects\\Music\\img\\fondo madera.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 380);

        jMenu2.setText("|||");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Menu");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        opciones.add(jMenu2);

        setJMenuBar(opciones);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verListaActionPerformed

        hilo1 = new Thread(this);

        hilo1.start();

    }//GEN-LAST:event_verListaActionPerformed

    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        if (ct == hilo1) {

            selecionarDisco();

        }
        if (ct == hilo2) {

            cortar = cortar.substring(0, cortar.indexOf(".m"));
            NombreMusic.setText(cortar);

        }
        if (ct == hilo3) {
            JOptionPane.showMessageDialog(null, "se ha pausado la cancion" + archivo);
       

        }

        if (ct == hilo4) {
            try {
                cambiarImagen();
            } catch (InterruptedException ex) {
                Logger.getLogger(MusicGalery.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }

    public void selecionarDisco() {
if(activo==true){
reproductor.close();

}
        JFileChooser Seleccionar = new JFileChooser("C:/Users/victorhugo/Documents/victor Lenovo/Nueva carpeta/music");
        int n = Seleccionar.showOpenDialog(null);
        if (n == JFileChooser.APPROVE_OPTION) {
            archivo = Seleccionar.getSelectedFile();
            //System.out.println(""+archivo.getName());
            try {
            reproductor = new AdvancedPlayer(new FileInputStream(archivo));
                hilo2 = new Thread(this);
                pause.setText("[]");
                cortar = archivo.getName();
                hilo2.start();
 activo= true;
              reproductor.play();
             
            } catch (Exception ex) {
                System.out.println(" error al reproducir el archivo '" + archivo.getName() + "' \n"+ex);

            }catch (ExceptionInInitializerError ex) {
                System.out.println(" error al reproducir el archivo '" + archivo.getName() + "'");

            }}
    }

    public void pause() throws JavaLayerException, InterruptedException {
if (Pausec==false) {NombreMusic.setText("No Audio");
        pause.setText("|>");
}else {

reproductor.play();
        NombreMusic.setText("No Audio");
        pause.setText("||");
}
        

    }
    private void pauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseActionPerformed
        hilo3.start();

    }//GEN-LAST:event_pauseActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        LLamarLista();

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jPanel1.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        floco.getMaxLabel();

    }//GEN-LAST:event_jButton5ActionPerformed
        //GUardar MArcadores
    double marca;
    int marcacont=0;
    private void MarcadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcadoresActionPerformed

//        String marcador = archivo.getName();
//        String direccion = "" + archivo;
//
//        try {
//            cn.StartQuery("insert into Lista_Guardada values (01,Lst_gd_seq.nextval,'" + marcador + "','" + direccion + "')");
//        } catch (Exception exe) {
//        }
//        LLamarLista();
//        String data[][] = {};
//      
        marcacont= marcacont+1;
      
      
 marcador.add( new Lista(archivo.getName(), archivo.toString(),"10"+marcacont+""));
 String guardar="";
 for(int i=0;i<marcador.size();i++){
 guardar=guardar+"\n"+marcador.get(i).getCod_cancion()+") "+marcador.get(i).getNombre()+"  -  "+ marcador.get(i).getDireccion()+"\n";
 }
 JOptionPane.showMessageDialog(null,guardar+"");
        
        

    }//GEN-LAST:event_MarcadoresActionPerformed

    public void LLamarLista() {
        try {
            cn.StartQuery("select count(*) from Lista_Guardada");
            String[] tamaño = cn.SacarQuery("count(*)", 3);
            JOptionPane.showMessageDialog(rootPane, "cantidad de canciones  " + tamaño[0]);
            cn.StartQuery("select nombre,dir from Lista_Guardada ");
            String[] nombres = cn.SacarQuery("nombre", Integer.parseInt(tamaño[0]));
            JOptionPane.showMessageDialog(null, nombres[0] + "\n" + nombres[1]);
            cn.StartQuery("select nombre,dir from Lista_Guardada ");
            String[] direc = cn.SacarQuery("dir", Integer.parseInt(tamaño[0]));
            JOptionPane.showMessageDialog(null, direc[0] + "\n" + direc[1]);
            System.out.println("cancion :" + nombres[0] + "   " + direc[0]);
            System.out.println("cancion :" + nombres[1] + "   " + direc[1]);
            System.out.println("cancion :" + nombres[2] + "   " + direc[2]);
            llenarLista(nombres, direc, Integer.parseInt(tamaño[0]));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error" + ex);
        }
    }

    public void llenarLista(String[] nombre, String[] direccion, int tamaño) {
        String data[][] = {};
        String col[] = {"pregunta", "A"};
        modelo = new DefaultTableModel(data, col);

        for (int i = 0; i < tamaño; i++) {

            modelo.insertRow(i, new Object[]{});
            modelo.setValueAt(nombre[i], i, 0);
            modelo.setValueAt(direccion[i], i, 1);

        }
        jTable1.setModel(modelo);
    }
    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        Vol.setText("Vol : " + jSlider1.getValue());

    }//GEN-LAST:event_jSlider1StateChanged

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        JOptionPane.showMessageDialog(rootPane, "debes escoger una cancion  " + jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        cortar = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        JOptionPane.showMessageDialog(rootPane, cortar);
        try {
            hilo2 = new Thread(this);

            hilo2.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "no se pudo llamar al hilo 2");
        }

    }//GEN-LAST:event_jTable1MouseClicked

   public void cambiarImagen() throws InterruptedException {
        System.out.print("ingreso");

        for (int i = 0; i <= 6; i++) {
            Thread.sleep(10000);

            switch (i) {
                case 0:
                    img1.setVisible(true);
                    img2.setVisible(false);
                    img3.setVisible(false);
                    img4.setVisible(false);
                    img5.setVisible(false);
                    img6.setVisible(false);

                    System.out.print("0");
                    break;
                case 1:
                    img1.setVisible(false);
                    img2.setVisible(true);
                    img3.setVisible(false);
                    img4.setVisible(false);
                    img5.setVisible(false);
                    img6.setVisible(false);

                    break;
                case 2:
                    img1.setVisible(false);
                    img2.setVisible(false);
                    img3.setVisible(true);
                    img4.setVisible(false);
                    img5.setVisible(false);
                    img6.setVisible(false);

                    break;
                case 3:
                    img1.setVisible(false);
                    img2.setVisible(false);
                    img3.setVisible(false);
                    img4.setVisible(true);
                    img5.setVisible(false);
                    img6.setVisible(false);

                    break;
                case 4:
                    img1.setVisible(false);
                    img2.setVisible(false);
                    img3.setVisible(false);
                    img4.setVisible(false);
                    img5.setVisible(true);
                    img6.setVisible(false);

                    break;
                case 5:
                    img1.setVisible(false);
                    img2.setVisible(false);
                    img3.setVisible(false);
                    img4.setVisible(false);
                    img5.setVisible(false);
                    img6.setVisible(true);

                    break;

            }
            if (i == 5) {
                i = 0;
            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicGalery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicGalery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicGalery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicGalery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
conector c = new conector();
        new MusicGalery( c).setVisible(true);
        
        /* Create and display the form */
//        new MusicGalery().setVisible(true);

    }
    /*data base :
     MUSICGALERY
     MUSICGALERYBDD
     mysound3*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Marcadores;
    private javax.swing.JLabel NombreMusic;
    private javax.swing.JLabel Vol;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuBar opciones;
    private javax.swing.JButton pause;
    private javax.swing.JButton verLista;
    // End of variables declaration//GEN-END:variables
}
